In [2]:

import pandas as pd

In [9]:
genome_scores = pd.read_csv('data/genome-scores.zip',compression='zip', sep=',')
print(genome_scores.info())
genome_scores.head(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11709768 entries, 0 to 11709767
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   movieId    int64
 1   tagId      int64
 2   relevance  float64
dtypes: float64(1), int64(2)
memory usage: 268.0 MB
None

   movieId  tagId  relevance
0        1      1    0.02500
1        1      2    0.02500
2        1      3    0.05775
3        1      4    0.09675

In [10]:
genome_tags = pd.read_csv('data/genome-tags.zip',compression='zip', sep=',')
print(genome_tags.info())
genome_tags.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1128 entries, 0 to 1127
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tagId   1128 non-null   int64
 1   tag     1128 non-null   object
dtypes: int64(1), object(1)
memory usage: 17.8+ KB
None

   tagId           tag
0      1           007
1      2  007 (series)
2      3  18th century
3      4         1920s
4      5         1930s

In [11]:
links = pd.read_csv('data/links.zip',compression='zip', sep=',')
print(links.info())
links.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  27278 non-null  int64
 1   imdbId   27278 non-null  int64
 2   tmdbId   27026 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 639.5 KB
None

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [12]:
movies = pd.read_csv('data/movies.zip',compression='zip', sep=',')
print(movies.info())
movies.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  27278 non-null  int64
 1   title    27278 non-null  object
 2   genres   27278 non-null  object
dtypes: int64(1), object(2)
memory usage: 639.5+ KB
None

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [13]:
tags = pd.read_csv('data/tags.zip',compression='zip', sep=',')
print(tags.info())
tags.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465564 entries, 0 to 465563
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     465564 non-null  int64
 1   movieId    465564 non-null  int64
 2   tag        465548 non-null  object
 3   timestamp  465564 non-null  int64
dtypes: int64(3), object(1)
memory usage: 14.2+ MB
None

   userId  movieId            tag   timestamp
0      18     4141    Mark Waters  1240597180
1      65      208      dark hero  1368150078
2      65      353      dark hero  1368150079
3      65      521  noir thriller  1368149983
4      65      592      dark hero  1368150078

In [14]:
rating1 = pd.read_csv('data/ratings_part1.zip',compression='zip', sep=',')
print(rating1.info())
rating1.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000132 entries, 0 to 10000131
Data columns (total 5 columns):
 #   Column      Dtype
---  ------      -----
 0   Unnamed: 0  int64
 1   userId      int64
 2   movieId     int64
 3   rating      float64
 4   timestamp   int64
dtypes: float64(1), int64(4)
memory usage: 381.5 MB
None

   Unnamed: 0  userId  movieId  rating  timestamp
0    10000131   69141     1357     5.0  914691116
1    10000132   69141     1411     4.0  914690829
2    10000133   69141     1704     5.0  914691145
3    10000134   69141     1921     4.0  914692138
4    10000135   69141     1961     4.0  914690408